# Generated by Django 4.2.1 on 2023-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='postponed_cound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
