# Generated by Django 4.2.1 on 2023-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make', models.CharField(max_length=150)),
                ('engine_hp', models.FloatField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
