# Generated by Django 4.2.1 on 2023-05-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boats',
            new_name='Boat',
        ),
    ]
