# Generated by Django 4.2.1 on 2023-05-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_tasting_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='drink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasting', to='drinks.drink'),
        ),
    ]
