# Generated by Django 4.2.1 on 2023-05-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_alter_tasting_drink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasting',
        ),
    ]
